import { useMemo, useState } from 'react';
import { ArrowRight, Check, CircleAlert, Download, FileJson, GitFork, Pencil, Play, Plus, ShieldCheck } from 'lucide-react';
import { TOOL_CATALOG, simulateWorkflow, validateWorkflow, type Scenario, type WorkflowSpec } from './workflow-domain';
import { exportHandoff, serializeBackup, type Plan, type RunRecord } from './workspace';
import { WorkflowGraph } from './WorkflowGraph';
import { CATEGORY, date, downloadFile, ErrorMessage, Modal, STATUS } from './ui';

export function EditorView({ plan, editNode, addNode, editSettings, next }: { plan: Plan; editNode: (id: string) => void; addNode: () => void; editSettings: () => void; next: () => void }) {
  const [selected, setSelected] = useState(plan.workflow.nodes[0]?.id || '');
  const check = useMemo(() => validateWorkflow(plan.workflow), [plan.workflow]);
  const node = plan.workflow.nodes.find(n => n.id === selected) || plan.workflow.nodes[0];
  const tool = TOOL_CATALOG.find(t => t.name === node?.tool);
  const issues = check.issues.filter(i => i.node_id === node?.id);
  return <><div className="view-heading"><div><span className="eyebrow">01 / DESIGN THE FLOW</span><h2>每一步，都知道为什么在这里。</h2><p>选择节点查看设置，调整输入数据、先后顺序与失败路径。</p></div><button className="primary" onClick={addNode} disabled={plan.workflow.nodes.length >= 20}><Plus/>添加步骤</button></div>
    <div className="workflow-meta"><div><span className="meta-label">流程入口</span><strong>{plan.workflow.trigger.type === 'manual' ? '手动触发' : plan.workflow.trigger.type === 'cron' ? '定时触发声明' : '事件触发声明'}</strong><small>{plan.workflow.trigger.expression || plan.workflow.trigger.event || '试跑时由你启动'}</small></div><div><span className="meta-label">预期结果</span><p>{plan.workflow.description}</p></div><button className="secondary" onClick={editSettings}><Pencil/>编辑方案说明</button></div>
    <div className="edit-grid"><section className="flow-panel"><WorkflowGraph workflow={plan.workflow} selected={node?.id || ''} select={setSelected} badIds={new Set(check.issues.filter(i => i.level === 'error' && i.node_id).map(i => i.node_id!))}/><div className="step-list" aria-label="流程步骤列表">{plan.workflow.nodes.map((n, i) => <button key={n.id} onClick={() => setSelected(n.id)} aria-pressed={node?.id === n.id}><span>{String(i + 1).padStart(2, '0')}</span><div><strong>{TOOL_CATALOG.find(t => t.name === n.tool)?.description || n.tool}</strong><small>{n.id} · {n.depends_on.length ? `依赖 ${n.depends_on.join('、')}` : '入口步骤'}</small></div><ArrowRight/></button>)}</div></section>
    {node && <aside className="node-inspector"><div className="inspector-head"><span className="eyebrow">STEP / {node.id}</span><span className="tag">{tool ? CATEGORY[tool.category] : '待修正工具'}</span></div><h3>{tool?.description || node.tool}</h3><code>{node.tool}</code><dl className="node-params">{Object.entries(node.arguments).map(([key, value]) => <div key={key}><dt>{tool?.parameters[key]?.description || key}</dt><dd>{typeof value === 'string' ? value : JSON.stringify(value)}</dd></div>)}{!Object.keys(node.arguments).length && <p className="muted">尚未填写参数。</p>}</dl><div className="node-policy"><p><GitFork/>{node.when || '不设条件'}</p><p><ShieldCheck/>{node.requires_approval || tool?.risk === 'approval' || tool?.risk === 'notify' ? '执行前等待确认' : '可自动进入下一步'}</p><p>失败后额外重试 {node.retry.max_attempts} 次{node.on_failure ? `，再调用 ${node.on_failure.tool}` : ''}</p></div>{issues.map((i, index) => <p className={i.level === 'error' ? 'error-message' : 'warning'} key={index}>{i.message}</p>)}<button className="primary" onClick={() => editNode(node.id)}><Pencil/>编辑这个步骤</button><p className="muted">当前展示的是流程定义，工具尚未运行。</p></aside>}</div>
    <div className="next-action"><p>{check.valid ? '结构已通过检查，可以继续查看提示并试跑。' : `${check.issues.filter(i => i.level === 'error').length} 项问题需要处理，可以逐项定位。`}</p><button className="secondary" onClick={next}>检查与修正<ArrowRight/></button></div>
  </>;
}

export function ChecksView({ plan, editNode, editSettings, next }: { plan: Plan; editNode: (id: string) => void; editSettings: () => void; next: () => void }) {
  const check = useMemo(() => validateWorkflow(plan.workflow), [plan.workflow]);
  return <><div className="view-heading"><div><span className="eyebrow">02 / CHECK BEFORE RUNNING</span><h2>{check.valid ? '结构可运行，业务含义由你确认。' : '先把这些问题处理好。'}</h2><p>检查直接来自当前方案，不沿用上一版结果。</p></div><span className={`status-badge ${check.valid ? 'succeeded' : 'failed'}`}>{check.valid ? '检查通过' : '暂不能试跑'}</span></div>
    <div className="check-stages">{[{ title: '流程结构', value: check.schema_valid, sub: '格式、节点与运行策略' }, { title: '依赖关系', value: check.dag_valid, sub: '顺序、循环与数据来源' }, { title: '工具与参数', value: check.tools_valid, sub: '工具清单、必填项与类型' }].map(s => <article key={s.title}><span className={s.value ? 'check-icon' : 'bad-icon'}>{s.value ? <Check/> : <CircleAlert/>}</span><div><h3>{s.title}</h3><p>{s.sub}</p></div><strong>{s.value ? '通过' : '待修正'}</strong></article>)}</div>
    <div className="validation-list">{check.issues.map((issue, i) => <article key={i} className={issue.level}><span className="tag">{issue.level === 'error' ? '需修正' : '请确认'}</span><div><h3>{issue.message}</h3><p>{issue.node_id ? `步骤 ${issue.node_id}` : '方案设置'}{issue.path ? ` · ${issue.path}` : ''}</p></div><button className="secondary" onClick={() => issue.node_id ? editNode(issue.node_id) : editSettings()}>去修改<ArrowRight/></button></article>)}</div>
    {check.valid && <div className="ready-panel"><ShieldCheck/><div><h3>下一步，用不同情境检查这份方案。</h3><p>结构通过只说明规则检查未发现阻塞。高低风险、审批拒绝和工具失败可能产生不同结果。</p><button className="primary" onClick={next}><Play/>进入沙箱试跑</button></div></div>}
    <details className="advanced"><summary>查看节点执行顺序</summary><p>{check.topological_order.join(' → ') || '修正依赖后才能计算执行顺序。'}</p><small>这是满足依赖的一种顺序，不代表真实并发执行时间。</small></details>
  </>;
}

export function RunView({ plan, start, decide, checkFirst }: { plan: Plan; start: (s: Scenario) => void; decide: (key: string, decision: 'approve' | 'reject') => void; checkFirst: () => void }) {
  const active = plan.runs.find(r => r.id === plan.activeRunId);
  const [risk, setRisk] = useState<Scenario['risk']>(active?.scenario.risk || 'high'); const [failure, setFailure] = useState(''); const [failureCount, setFailureCount] = useState('1'); const [error, setError] = useState('');
  const checked = useMemo(() => validateWorkflow(plan.workflow), [plan.workflow]);
  const result = useMemo(() => active ? simulateWorkflow(active.workflow, active.scenario, active.decisions) : null, [active]);
  const waiting = result?.trace.filter(t => t.event === 'waiting_approval' && t.decision_key) || [];
  return <><div className="view-heading"><div><span className="eyebrow">03 / TEST THE EXCEPTIONS</span><h2>让例外先在这里发生。</h2><p>使用固定虚拟数据试跑；不连接真实邮箱、群聊或业务系统。</p></div><span className="tag">无外部写操作</span></div>
    <div className="scenario-panel"><div className="scenario-heading"><h3>这次试跑的情境</h3><p>改变情境后，点击重新试跑才会产生新记录。</p></div><div className="form-grid"><label className="field">模拟风险等级<select value={risk} onChange={e => setRisk(e.target.value as Scenario['risk'])}><option value="high">高风险</option><option value="medium">中风险</option><option value="low">低风险</option></select><small>影响 risk.classify 的模拟输出。</small></label><label className="field">模拟哪个步骤失败<select value={failure} onChange={e => setFailure(e.target.value)}><option value="">不注入故障</option>{plan.workflow.nodes.map(n => <option value={n.id} key={n.id}>{n.id} · {TOOL_CATALOG.find(t => t.name === n.tool)?.description || n.tool}</option>)}</select></label><label className="field">失败情境<select value={failureCount} onChange={e => setFailureCount(e.target.value)} disabled={!failure}><option value="1">第一次失败，之后成功</option><option value="2">前两次失败，之后成功</option><option value="always">持续失败</option></select></label></div><div className="actions">{checked.valid ? <button className="primary" onClick={() => { try { start({ risk, failures: failure ? { [failure]: failureCount === 'always' ? 'always' : Number(failureCount) } : {} }); setError(''); } catch (e) { setError(e instanceof Error ? e.message : '试跑未启动'); } }}><Play/>{active ? '按当前情境重新试跑' : '开始沙箱试跑'}</button> : <button className="secondary" onClick={checkFirst}>先修正检查问题<ArrowRight/></button>}<span className="muted">重试次数来自各节点设置。新试跑不会沿用审批决定。</span></div><ErrorMessage message={error}/></div>
    {!active && <div className="empty-state"><Play/><h3>当前方案还没有试跑记录</h3><p>{plan.runs.length ? '方案已经修改，旧试跑已归档。请为当前版本重新试跑。' : '从高风险情境开始，观察流程在哪里等待确认。'}</p></div>}
    {active && result && <><div className="run-heading"><div><span className="eyebrow">RUN / R{active.revision} · {date(active.startedAt)}</span><h3>本次结果</h3></div><span className={`status-badge ${result.status}`}>{STATUS[result.status]}</span></div><p className="run-context">本记录情境：{({ high: '高风险', medium: '中风险', low: '低风险' })[active.scenario.risk]} · {Object.entries(active.scenario.failures).map(([id, n]) => `${id} ${n === 'always' ? '持续失败' : `前 ${n} 次失败`}`).join('；') || '未注入故障'}</p>
      {waiting.map((item, i) => <article className="approval-card" key={`${item.decision_key}-${i}`}><ShieldCheck/><div><span className="eyebrow">YOUR DECISION IS NEEDED</span><h3>{TOOL_CATALOG.find(t => t.name === item.tool)?.description || item.tool} · {item.node_id}</h3><p>{item.message}</p><details><summary>确认前检查输入与目标</summary><pre>{JSON.stringify(item.decision_key?.endsWith(':failure') ? active.workflow.nodes.find(n => n.id === item.node_id)?.on_failure : active.workflow.nodes.find(n => n.id === item.node_id)?.arguments, null, 2)}</pre>{item.input_from && <p>输入来源：{item.input_from}</p>}</details><div className="actions"><button className="secondary" onClick={() => { try { decide(item.decision_key!, 'reject'); setError(''); } catch (e) { setError(String(e)); } }}>拒绝这一步</button><button className="primary" onClick={() => { try { decide(item.decision_key!, 'approve'); setError(''); } catch (e) { setError(String(e)); } }}><Check/>确认并继续模拟</button></div></div></article>)}
      <RunDetails record={active}/>
    </>}
  </>;
}

export function RunDetails({ record }: { record: RunRecord }) {
  const result = useMemo(() => simulateWorkflow(record.workflow, record.scenario, record.decisions), [record]);
  return <><div className="execution-list">{result.nodes.map(n => <details key={n.node_id} className={`execution-node ${n.status}`}><summary><span className="execution-dot"/><div><strong>{TOOL_CATALOG.find(t => t.name === n.tool)?.description || n.tool}</strong><small>{n.node_id} · {n.attempts} 次尝试</small></div><span className={`status-badge ${n.status}`}>{STATUS[n.status]}</span></summary><div className="execution-body"><p>{n.message}</p>{n.input_from && <p>数据来自：<code>{n.input_from}</code></p>}<h4>模拟输出</h4><pre>{n.output ? JSON.stringify(n.output, null, 2) : '该节点尚无输出。'}</pre>{n.failure_handler && <p>失败处理：{n.failure_handler.tool} · {STATUS[n.failure_handler.status]}</p>}</div></details>)}</div><details className="advanced trace-details"><summary>查看完整逐步轨迹 · {result.trace.length} 条</summary><ol>{result.trace.map(t => <li key={t.index}><code>{t.node_id}</code><span>{t.message}</span>{t.attempt !== undefined && <small>第 {t.attempt} 次尝试</small>}</li>)}</ol></details></>;
}

export function DeliveryView({ plan }: { plan: Plan }) {
  const [selected, setSelected] = useState(plan.runs[0]?.id || ''); const [error, setError] = useState('');
  const record = plan.runs.find(r => r.id === selected);
  function download(kind: 'spec' | 'backup' | 'report') { try { if (kind === 'spec') downloadFile(`${plan.title}-WorkflowSpec.json`, JSON.stringify(plan.workflow, null, 2), 'application/json'); else if (kind === 'backup') downloadFile(`${plan.title}-完整备份.json`, serializeBackup(plan), 'application/json'); else downloadFile(`${plan.title}-交接记录.md`, exportHandoff(plan, record), 'text/markdown;charset=utf-8'); setError(''); } catch (e) { setError(e instanceof Error ? e.message : '导出失败'); } }
  return <><div className="view-heading"><div><span className="eyebrow">04 / LEAVE A TRACE</span><h2>交付方案，也留下判断依据。</h2><p>工作流定义用于技术接入，完整备份用于续写；试跑记录绑定当时的方案。</p></div></div>
    <div className="export-options"><article><FileJson/><h3>当前工作流</h3><p>WorkflowSpec v1 JSON，包含工具、参数、依赖和策略。</p><button className="secondary" onClick={() => download('spec')}><Download/>导出工作流 JSON</button></article><article><Download/><h3>完整方案备份</h3><p>包含需求、当前流程、试跑记录和待确认进度，可恢复。</p><button className="secondary" onClick={() => download('backup')}><Download/>下载完整备份</button></article><article><Check/><h3>方案交接记录</h3><p>当前方案说明与下方选定试跑的快照、检查及逐步轨迹。</p><button className="primary" onClick={() => download('report')}><Download/>导出交接记录</button></article></div><ErrorMessage message={error}/>
    <div className="section-heading"><div><h3>最近的试跑记录</h3><p>最多保留 10 次。历史审批不能用于新方案，保留的是当时的状态。</p></div></div>
    {!plan.runs.length ? <div className="empty-state"><p>还没有试跑。可以先导出定义，或回到沙箱验证。</p></div> : <div className="history-grid"><div className="history-list">{plan.runs.map(r => { const result = simulateWorkflow(r.workflow, r.scenario, r.decisions); return <button key={r.id} onClick={() => setSelected(r.id)} aria-pressed={r.id === selected}><strong>方案 R{r.revision} · {STATUS[result.status]}</strong><small>{date(r.startedAt)} · {r.scenario.risk}{r.revision !== plan.revision ? ' · 历史方案' : ' · 当前方案'}</small></button>; })}</div>{record && <section className="history-detail"><div className="notice"><strong>记录基于 R{record.revision}，当前方案为 R{plan.revision}</strong><p>风险：{record.scenario.risk} · 故障：{JSON.stringify(record.scenario.failures)}</p></div><RunDetails record={record}/><details className="advanced"><summary>查看本记录的流程快照</summary><pre>{JSON.stringify(record.workflow, null, 2)}</pre></details></section>}</div>}
    <details className="advanced"><summary>查看当前工作流 JSON</summary><pre>{JSON.stringify(plan.workflow, null, 2)}</pre></details>
  </>;
}

export function SettingsDialog({ plan, close, save }: { plan: Plan; close: () => void; save: (title: string, brief: string, workflow: WorkflowSpec) => void }) {
  const [title, setTitle] = useState(plan.title), [brief, setBrief] = useState(plan.brief), [workflow, setWorkflow] = useState(structuredClone(plan.workflow)), [error, setError] = useState('');
  return <Modal title="方案说明与触发方式" close={close}><label className="field">方案名称<input value={title} maxLength={80} onChange={e => setTitle(e.target.value)}/></label><label className="field">业务需求<textarea rows={4} value={brief} maxLength={600} onChange={e => setBrief(e.target.value)}/><small>修改说明不会自动生成节点。需要重新起草时使用方案菜单。</small></label><label className="field">预期结果<textarea rows={3} value={workflow.description} maxLength={300} onChange={e => setWorkflow({ ...workflow, description: e.target.value })}/></label><label className="field">触发方式<select value={workflow.trigger.type} onChange={e => setWorkflow({ ...workflow, trigger: { type: e.target.value as 'manual' | 'cron' | 'event' } })}><option value="manual">手动启动</option><option value="cron">定时触发声明</option><option value="event">事件触发声明</option></select></label>{workflow.trigger.type === 'cron' && <label className="field">Cron 表达式<input value={workflow.trigger.expression || ''} placeholder="0 9 * * 1" onChange={e => setWorkflow({ ...workflow, trigger: { ...workflow.trigger, expression: e.target.value } })}/></label>}{workflow.trigger.type === 'event' && <label className="field">事件名<input value={workflow.trigger.event || ''} placeholder="feedback.created" onChange={e => setWorkflow({ ...workflow, trigger: { ...workflow.trigger, event: e.target.value } })}/></label>}<p className="notice">公开沙箱只保存触发声明，不会创建定时任务或监听真实事件。</p><ErrorMessage message={error}/><div className="modal-actions"><button className="secondary" onClick={close}>取消</button><button className="primary" disabled={!title.trim() || workflow.description.trim().length < 2} onClick={() => { try { save(title.trim(), brief, workflow); } catch (e) { setError(e instanceof Error ? e.message : '设置未保存'); } }}>保存方案设置</button></div></Modal>;
}
